from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[1];D=json.loads((R/'content.json').read_text(encoding='utf-8'));S=D['services']
esc=html.escape
names={36:'Air Liquide',37:'Ayassa Fombella',38:'Balanz',39:'Banco Galicia',40:'Bayer',41:'Contract Workplaces',42:'Laboratorio Elea Phoenix',43:'Enarsa',44:'Ford',45:'Haleon',46:'HIT Cowork',47:'Mercado Libre',49:'PwC',50:'Raízen',51:'Rubinat',52:'Santander',53:'Shell',54:'Smurfit Kappa',55:'Telecentro',56:'TGN',57:'TGS',58:'UBA',59:'Universidad de Palermo',60:'Swiss Medical'}
def paras(lines):return ''.join('<p>'+esc(t)+'</p>' for t in lines)
def label(n,t):return f'<div class="eyebrow"><span>{n}</span>{t}</div>'
def image(key,alt,prefix='',hero=False):
 src=f'{prefix}assets/{key}.webp';responsive=f' srcset="{prefix}assets/{key}-mobile.webp 800w, {src} 1800w" sizes="(max-width: 760px) 100vw, 65vw"' if hero else ''
 return f'<img src="{src}"{responsive} alt="{esc(alt)}" '+('fetchpriority="high"' if hero else 'loading="lazy"')+' width="1536" height="1024">'
def btn(text,target='#contacto',secondary=False):return f'<a class="button {"secondary" if secondary else ""}" href="{target}">{text}<span aria-hidden="true">↗</span></a>'
def logos(ids,b):return '<div class="logos">'+''.join(f'<figure class="{"logo-dark-tile" if i in [43,46,55,58] else ""}"><img src="{b}assets/client-{i}.webp" alt="{names[i]}" width="200" height="80" loading="lazy"><figcaption>{names[i]}</figcaption></figure>' for i in ids)+'</div>'
def process(steps,end='Cada proyecto se aborda con un proceso claro, trazable y adaptable a la complejidad de cada necesidad.'):
 return '<section class="section process" id="metodo">'+label('04','MÉTODO DE TRABAJO')+'<div class="section-heading"><h2>Cómo trabajamos</h2><p>Del diagnóstico a una decisión<br>técnicamente fundamentada.</p></div><div class="steps">'+''.join(f'<article><span class="step-number">0{j+1}</span><h3>{esc(t)}</h3><p>{esc(v)}</p></article>' for j,(t,v) in enumerate(steps))+'</div><p class="section-note">'+esc(end)+'</p></section>'
def contact(selected=''):
 opts=''.join(f'<option {"selected" if s["name"]==selected else ""}>{s["name"]}</option>' for s in S)
 return '<section class="section contact" id="contacto"><div>'+label('HABLEMOS','CONTACTO')+'<h2>El próximo paso<br>empieza con una<br><em>conversación.</em></h2><p>¿Tenés un proyecto o necesitás resolver un problema técnico? Contanos brevemente la situación y coordinemos una conversación.</p><a class="email" href="mailto:hola@sabater.com.ar">hola@sabater.com.ar ↗</a><p class="location">Buenos Aires, Argentina<br>Proyectos en todo el país.</p><div class="contact-links"><button data-pending="WhatsApp">WhatsApp ↗</button><button data-pending="LinkedIn">LinkedIn ↗</button></div></div><form id="contact-form"><div class="form-grid"><label>Nombre y apellido<input name="nombre" autocomplete="name" required placeholder="Tu nombre"></label><label>Empresa<input name="empresa" autocomplete="organization" placeholder="Nombre de la empresa"></label><label>Email<input type="email" name="email" autocomplete="email" required placeholder="nombre@empresa.com"></label><label>Teléfono<input type="tel" name="telefono" autocomplete="tel" placeholder="Código de área y número"></label></div><label>Servicio de interés<select name="servicio"><option value="" '+('selected' if not selected else '')+' disabled>Seleccioná un servicio</option>'+opts+'<option>Otro / No estoy seguro</option></select></label><label>Contanos sobre tu proyecto<textarea name="mensaje" required rows="3" placeholder="¿Qué necesitás resolver?"></textarea></label><button class="button" type="submit">Enviar consulta <span aria-hidden="true">↗</span></button><p class="form-note">Formulario de demostración. No se envían ni almacenan datos.</p><p id="form-status" role="status"></p></form></section>'
def closing(title,text,cta):return '<section class="closing">'+label('SIGUIENTE PASO','DEFINAMOS EL CAMINO')+f'<h2>{esc(title)}</h2><p>{esc(text)}</p>'+btn(cta)+'<button class="text-button" data-pending="WhatsApp">Escribinos por WhatsApp ↗</button></section>'
def page(body,title,desc,b='',active='',hero='home'):
 nav=''.join(f'<a href="{b}index.html#{anchor}">{text}</a>' for anchor,text in [('inicio','Inicio'),('servicios','Servicios'),('nosotros','Nosotros'),('experiencia','Experiencia'),('conocimiento','Conocimiento')])
 schema={'@context':'https://schema.org','@type':'Organization','name':'SABATER Ingeniería','url':'https://estudioideamos.github.io/sabater-ingenieria-demo/','logo':'https://estudioideamos.github.io/sabater-ingenieria-demo/assets/logo-dark.webp','email':'hola@sabater.com.ar','areaServed':'Argentina'}
 return f'''<!doctype html><html lang="es-AR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title}</title><meta name="description" content="{esc(desc)}"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#181A1B"><meta property="og:title" content="{title}"><meta property="og:description" content="{esc(desc)}"><meta property="og:image" content="https://estudioideamos.github.io/sabater-ingenieria-demo/assets/{hero}.webp"><link rel="icon" href="{b}assets/favicon.webp"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;450;500;550;600;650;700&family=Manrope:wght@400;500;600;650;700;750;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="{b}styles.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><script src="{b}app.js" defer></script></head><body><a class="skip" href="#contenido">Saltar al contenido</a><header><a href="{b}index.html" class="brand" aria-label="Sabater Ingeniería — Inicio"><img src="{b}assets/logo-light.webp" alt="SABATER Ingeniería" width="310" height="64"></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Abrir menú">Menú <span>＋</span></button><nav id="navigation" aria-label="Navegación principal">{nav}<a class="nav-contact" href="#contacto">Hablemos <span>↗</span></a></nav></header><main id="contenido">{body}</main><footer><div class="footer-top"><a href="{b}index.html"><img src="{b}assets/logo-light.webp" alt="Sabater Ingeniería" width="310" height="64"></a><p>Consultoría especializada<br>en acústica y vibraciones.</p><a href="#inicio">Volver arriba ↑</a></div><div class="footer-links"><a href="{b}index.html#servicios">Servicios</a><a href="{b}index.html#nosotros">Nosotros</a><a href="#metodo">Cómo trabajamos</a><a href="{b}index.html#conocimiento">Conocimiento / Blog</a><a href="#contacto">Contacto</a></div><div class="footer-bottom"><span>© 2026 SABATER Ingeniería. Todos los derechos reservados.</span><span>Demo de diseño · Ideamos</span></div></footer><button class="floating-contact" data-pending="WhatsApp" aria-label="Contacto por WhatsApp"><svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M21 11.5a9 9 0 0 1-13.5 7.8L3 21l1.7-4.5A9 9 0 1 1 21 11.5Z"/><path d="M8 7c0 5 4 9 9 9l1-3-3-1-1 1-3-3 1-1-1-3-3 1Z"/></svg></button><dialog id="pending-dialog"><button class="dialog-close" aria-label="Cerrar">×</button><div class="eyebrow">DEMO · CONTACTO PENDIENTE</div><h2 id="pending-title">Contacto</h2><p>Estamos preparando este canal. El dato definitivo está pendiente de entrega por parte del cliente.</p><button class="button dialog-done">Entendido <span>↗</span></button></dialog></body></html>'''
body='<section class="hero" id="inicio"><div class="hero-image">'+image('home','Medición acústica en un entorno industrial',hero=True)+'</div><div class="hero-content">'+label('SABATER INGENIERÍA','PRECISIÓN QUE TRANSFORMA')+'<h1>Ingeniería <br>especializada en <br><em>acústica</em> y <br>vibraciones<span class="title-dot">.</span></h1><p>Diagnosticamos problemas, evaluamos alternativas y desarrollamos soluciones para que cada decisión técnica esté respaldada por información confiable.</p><div class="hero-actions">'+btn('Hablemos de tu proyecto')+'<a class="text-link" href="#servicios">Conocé nuestros servicios ↓</a></div></div><div class="hero-bottom"><span>ACÚSTICA & VIBRACIONES</span><span>BUENOS AIRES · ARGENTINA</span><a href="#enfoque" aria-label="Explorar el sitio">EXPLORAR ↓</a></div></section>'
body+='<div class="service-strip">'+''.join(f'<a href="{s["slug"]}/"><span>0{n+1}</span>{s["short"]} <span>↗</span></a>' for n,s in enumerate(S))+'</div>'
body+='<section class="section intro" id="enfoque">'+label('01','NUESTRO ENFOQUE')+'<div><h2>Ingeniería para tomar<br><em>mejores decisiones.</em></h2><div class="intro-text">'+paras(D['intro'])+'</div></div></section>'
body+='<section class="section services" id="servicios">'+label('02','ESPECIALIDADES')+'<div class="section-heading"><h2>Cuatro especialidades.<br>Un mismo <em>criterio técnico.</em></h2><p>Servicios de ingeniería en acústica y vibraciones. Del diagnóstico a la definición técnica de la solución.</p></div><div class="service-grid">'
for n,s in enumerate(S):
 body+=f'<a class="service-card" href="{s["slug"]}/"><div class="card-image">'+image(s['key']+'-card',s['card'][0])+f'<span class="card-number">0{n+1} /</span><span class="card-arrow" aria-hidden="true">↗</span></div><div class="card-copy"><h3>{s["short"]}</h3><p>{s["card"][0]}</p><span class="card-link">Explorar especialidad <span>↗</span></span></div></a>'
body+='</div></section><section class="section why">'+label('03','POR QUÉ SABATER INGENIERÍA')+'<div class="why-layout"><h2>Certeros.<br><em>Confiables.</em><br>Impecables.</h2><div class="why-grid">'+''.join(f'<article><span class="small-number">0{j+1}</span><h3>{t}</h3><p>{v}</p></article>' for j,(t,v) in enumerate(D['why']))+'</div></div></section>'
body+=process(D['steps'])
body+='<section class="section about" id="nosotros">'+label('05','SOBRE SABATER INGENIERÍA')+'<div class="about-layout"><div class="experience-number">15<span>+</span><p>AÑOS DE EXPERIENCIA<br>EN INGENIERÍA ACÚSTICA</p></div><div><h2>Especialización.<br>Independencia.<br><em>Ingeniería con criterio.</em></h2>'+paras(D['about'])+'</div></div></section>'
body+='<section class="section experience" id="experiencia">'+label('06','TRAYECTORIA PROFESIONAL')+'<div class="section-heading"><h2>Experiencia<br>que nos respalda.</h2><p>A lo largo de más de 15 años de trayectoria profesional hemos participado en proyectos de ingeniería acústica para empresas, estudios y organizaciones de múltiples industrias.</p></div>'+logos([44,53,40,45,57,56,42,50,36,54,43,55],'')+'<p class="section-note">Industria · Oil & Gas · Minería · Automotriz · Telecomunicaciones · Arquitectura · Construcción · Farmacéutica · Salud · Servicios financieros.</p></section>'
body+='<section class="section knowledge" id="conocimiento">'+label('07','CONOCIMIENTO / BLOG')+'<div class="section-heading"><h2>La precisión empieza<br>por <em>entender.</em></h2><p>Explorá nuestro enfoque técnico por especialidad. Próximamente, artículos y nuevas perspectivas de ingeniería.</p></div><div class="knowledge-grid">'+''.join(f'<a href="{s["slug"]}/"><span>0{n+1} / GUÍA DE SERVICIO</span><h3>{t}</h3><span class="card-link">Conocer el enfoque ↗</span></a>' for n,(s,t) in enumerate(zip(S,['Entender el ruido antes de definir la solución.','Integrar la acústica desde el diseño.','Convertir mediciones en respaldo técnico.','Leer las señales antes de la falla.'])))+'</div></section>'
body+=closing('¿Tenés un problema de ruido, vibraciones o un proyecto que necesita una mirada especializada?','Contanos la situación. Podemos ayudarte a entender el problema, evaluar alternativas y definir el próximo paso con criterio técnico.','Hablemos de tu proyecto')+contact()
(R/'index.html').write_text(page(body,'SABATER Ingeniería | Ingeniería Acústica y Vibraciones','Ingeniería especializada en acústica y vibraciones para industrias, arquitectura y evaluaciones técnicas. Diagnóstico, medición, análisis e ingeniería.'),encoding='utf-8')
for n,s in enumerate(S):
 b='../';body='<section class="hero detail-hero" id="inicio"><div class="hero-image">'+image(s['key'],s['lead'],b,True)+'</div><div class="hero-content"><a class="breadcrumb" href="../index.html#servicios">← Servicios / '+s['short']+'</a>'+label('0'+str(n+1)+' / ESPECIALIDAD','SABATER INGENIERÍA')+'<h1>'+esc(s['name'])+'<span class="title-dot">.</span></h1><p class="detail-lead">'+esc(s['lead'])+'</p>'+btn(s['cta'])+'<a class="text-link" href="#metodo">Ver cómo trabajamos ↓</a></div><div class="hero-bottom"><span>DIAGNÓSTICO · ANÁLISIS · INGENIERÍA</span><span>CRITERIO TÉCNICO INDEPENDIENTE</span></div></section>'
 body+='<section class="section detail-intro">'+label('01','COMPRENDER EL CONTEXTO')+'<div>'+paras(s['intro'])+'</div></section><section class="section problems">'+label('02','PROBLEMAS QUE RESOLVEMOS')+'<div class="section-heading"><h2>Todo empieza por<br>entender el problema.</h2><div>'+paras(s['problemIntro'])+'</div></div><div class="problem-grid">'+''.join(f'<article><span class="small-number">0{j+1}</span><h3>{t}</h3><p>{v}</p></article>' for j,(t,v) in enumerate(s['problems']))+'</div><p class="pullquote">'+esc(s['problemEnd'])+'</p></section>'
 body+='<section class="section what">'+label('03','QUÉ HACEMOS')+'<div class="section-heading"><h2>'+s['whatTitle']+'</h2><div>'+paras(s['what'])+'</div></div><div class="sequence">'+''.join('<figure>'+image(s['key']+'-'+k,t,b)+f'<figcaption><span>0{j+1}</span>{t}</figcaption></figure>' for j,(k,t) in enumerate(zip(['medir','analizar','decidir'],s['sequence'])))+'</div></section>'
 body+=process(s['steps'],s['stepEnd'])
 body+='<section class="section experience" id="experiencia">'+label('05','INFORMACIÓN QUE RESPALDA DECISIONES')+'<div class="section-heading"><h2>'+('Qué aporta el análisis<br>de vibraciones.' if s['key']=='predictivo' else 'Experiencia y<br>respaldo técnico.')+'</h2><div>'+paras(s['experience'])+'</div></div>'+logos(s['logos'],b)
 if s.get('benefits'):body+='<div class="benefits">'+''.join('<p>'+esc(t)+'</p>' for t in s['benefits'])+'</div>'
 body+='<p class="section-note">'+s['sectors']+'</p></section><section class="section faq">'+label('06','PREGUNTAS FRECUENTES')+'<div class="faq-layout"><h2>Respuestas claras.<br><em>Desde el principio.</em></h2><div>'+''.join('<details><summary>'+esc(q)+'<span aria-hidden="true">＋</span></summary><p>'+esc(ans)+'</p></details>' for q,ans in s['faq'])+'</div></div></section>'
 body+=closing(*s['closing'],s['cta'])+contact(s['name']);out=R/s['slug'];out.mkdir(exist_ok=True);(out/'index.html').write_text(page(body,s['short']+' | SABATER Ingeniería',s['lead'],b,s['key'],s['key']),encoding='utf-8')
print('Built home and four service pages.')
